package bigclaw.db.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleid
     *
     * @mbggenerated
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.catagory
     *
     * @mbggenerated
     */
    private String catagory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.imgurl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.realselllink
     *
     * @mbggenerated
     */
    private String realselllink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleid
     *
     * @return the value of article.articleid
     *
     * @mbggenerated
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleid
     *
     * @param articleid the value for article.articleid
     *
     * @mbggenerated
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.catagory
     *
     * @return the value of article.catagory
     *
     * @mbggenerated
     */
    public String getCatagory() {
        return catagory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.catagory
     *
     * @param catagory the value for article.catagory
     *
     * @mbggenerated
     */
    public void setCatagory(String catagory) {
        this.catagory = catagory == null ? null : catagory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.imgurl
     *
     * @return the value of article.imgurl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.imgurl
     *
     * @param imgurl the value for article.imgurl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.realselllink
     *
     * @return the value of article.realselllink
     *
     * @mbggenerated
     */
    public String getRealselllink() {
        return realselllink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.realselllink
     *
     * @param realselllink the value for article.realselllink
     *
     * @mbggenerated
     */
    public void setRealselllink(String realselllink) {
        this.realselllink = realselllink == null ? null : realselllink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}